### ISSUE TITLE
Consider adding a map selection, simple example attached

### ISSUE THREAD

**Issue by takurkowski** [ua-snap/dash-cc#17]
<img width="1275" alt="Screen Shot 2020-04-23 at 3 25 22 PM" src="https://user-images.githubusercontent.com/1444284/80159614-f9fe0c80-8577-11ea-97a1-71178d8fde24.png">

**Comment by brucecrevensten** [comment]
No to adding a map :) but we should consider the ranges for display.

**Comment by cstephen** [comment]
We experimented with the idea of adding a min/max floating bar chart but ultimately decided this was not user friendly. Also, since the PRISM and CRU historical baseline datasets contain only monthly means, they do not have values comparable to the min/max values in the projected datasets.
