### ISSUE TITLE
Consider simply displaying ranges directly instead of adding bars to the plot. Example attached

### ISSUE THREAD

**Issue by takurkowski** [ua-snap/dash-cc#18]
Bars can be misinterpreted as error bars.

<img width="1275" alt="Screen Shot 2020-04-23 at 3 25 22 PM" src="https://user-images.githubusercontent.com/1444284/80159713-287be780-8578-11ea-85c7-01c6f4da10b6.png">

**Comment by cstephen** [comment]
This issue overlaps with #17 a little bit. We decided not to implement a floating bar chart. More details in ticket #17.
