### ISSUE TITLE
Switch to using central community list, use community IDs for passing values

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/dash-cc#23]
Switch to using the communities [here](https://github.com/ua-snap/geospatial-vector-veracity) but need to diff/confirm that all communities listed here are referenced there.

It looks like instead of constructing lists & passing values with community IDs, the names themselves are used, which is causing a lot of code (e.g. application.py / L~278-9 that could be simplified.

**Comment by cstephen** [comment]
The web app has been modified to use the unique community ID (e.g., AK124) for CSV filenames, and to use this as the value in the community selector dropdown form input. I still need to cross-reference to confirm all locations that had been included in the old tool are still present in the new tool (using the community list from the geospatial-vector-veracity repo).

**Comment by cstephen** [comment]
Communities from the old Community Charts tool have been cross-referenced with the communities in the new Community Charts tool. We have decided that it is okay to omit the 49 communities that were in the old tool vs. the new tool.
