### ISSUE TITLE
Make Decades Modular

### ISSUE THREAD

**Issue by alecbennett** [ua-snap/dash-cc#4]
Right now all decades are hard coded in.  This should be made dynamic, using a multi-dropdown, with some defaults set (Historical, 2010s, 2040s, 2060s, 2090s).  This will also reduce code duplication.

**Comment by brucecrevensten** [comment]
Eliminating any code duplication between the temp & precipitation configurations is a great idea and important for this issue 👍

**Comment by cstephen** [comment]
To simplify the user interface, we have decided to remove the decade input option and go back to hard-coding a subset of decades. Closing this issue.
